# Generated by Django 4.0.4 on 2022-05-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_cime', '0003_remove_payement_declaration_payement_num_avis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regime_impot',
            name='regime_impot',
            field=models.CharField(choices=[('RPM', 'RPM'), ('RPP', 'RPP'), ('REEL', 'REEL'), ('HRI', "Hors régime d'imposition")], max_length=20, verbose_name="Régime d'imposition"),
        ),
    ]
