# Generated by Django 4.0.4 on 2022-05-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_cime', '0004_alter_regime_impot_regime_impot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regime_impot',
            name='regime_impot',
            field=models.CharField(choices=[('RPM', 'RPM'), ('RPP', 'RPP'), ('REEL', 'REEL'), ('SIMPLIFIE', 'SIMPLIFIE'), ('HRI', "Hors régime d'imposition")], max_length=20, verbose_name="Régime d'imposition"),
        ),
    ]
