# Generated by Django 4.0.4 on 2022-06-02 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soft_cime', '0005_alter_regime_impot_regime_impot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_amr', models.PositiveBigIntegerField(unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('montant', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='contribuable',
            name='impots',
        ),
        migrations.AlterField(
            model_name='personnel',
            name='cellule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soft_cime.cellule'),
        ),
        migrations.CreateModel(
            name='Payement_AMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('montant', models.PositiveIntegerField()),
                ('amr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_cime.amr')),
                ('contribuable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_cime.contribuable')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_cime.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Part_Impot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('proprietaire', models.CharField(max_length=200)),
                ('taux', models.DecimalField(decimal_places=6, max_digits=7)),
                ('impot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_cime.impot')),
            ],
        ),
        migrations.AddField(
            model_name='amr',
            name='contribuable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_cime.contribuable'),
        ),
        migrations.AddField(
            model_name='amr',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_cime.personnel'),
        ),
    ]
