# Generated by Django 4.0.4 on 2022-06-03 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('soft_cime', '0006_amr_remove_contribuable_impots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payement_amr',
            name='recette',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payement_amr',
            name='recette_budg',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
