# Generated by Django 4.0.4 on 2022-06-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soft_cime', '0007_payement_amr_recette_payement_amr_recette_budg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impot_AMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('montant', models.PositiveIntegerField()),
                ('montant_budg', models.CharField(max_length=200)),
                ('recette', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='amr',
            name='montant',
        ),
        migrations.AddField(
            model_name='amr',
            name='impots',
            field=models.ManyToManyField(through='soft_cime.Impot_AMR', to='soft_cime.impot'),
        ),
        migrations.DeleteModel(
            name='Payement_AMR',
        ),
        migrations.AddField(
            model_name='impot_amr',
            name='amr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_cime.amr'),
        ),
        migrations.AddField(
            model_name='impot_amr',
            name='impot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_cime.impot'),
        ),
    ]
