# Generated by Django 4.0.4 on 2022-06-06 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('soft_cime', '0008_impot_amr_remove_amr_montant_amr_impots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impot_amr',
            name='recette',
        ),
        migrations.AddField(
            model_name='amr',
            name='recette',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
