# Generated by Django 4.0.4 on 2022-06-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_cime', '0009_remove_impot_amr_recette_amr_recette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impot_amr',
            name='montant_budg',
            field=models.PositiveIntegerField(),
        ),
    ]
