# Generated by Django 4.0.4 on 2022-06-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_cime', '0012_ug_activite'),
    ]

    operations = [
        migrations.AddField(
            model_name='impot',
            name='impot_nom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payement',
            name='date_virement',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='payement',
            name='etat',
            field=models.CharField(choices=[('Comptabilisé', 'Comptabilisé'), ('Non Comptabilisé', 'Non Comptabilisé')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payement',
            name='num_virement',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
