# Generated by Django 4.0.4 on 2022-06-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_cime', '0014_impot_projection_projection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projection',
            name='impots',
        ),
        migrations.AddField(
            model_name='projection',
            name='montant',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Impot_Projection',
        ),
    ]
