# Generated by Django 4.0.4 on 2022-06-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soft_cime', '0015_remove_projection_impots_projection_montant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projection_Impot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('montant', models.PositiveIntegerField(null=True)),
                ('impot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_cime.impot')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soft_cime.personnel')),
            ],
        ),
    ]
